### ISSUE TITLE
PGI install fails

### ISSUE THREAD

**Issue by vanderwb** [NCAR/HPCinstall#96]
The PGI installer creates some broken symlinks. Apparently this is by design. HPCInstall's hashing mechanism does not like this, however:

Hashdir:                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                          
  File "/glade/u/apps/dav/opt/hpcinstall/1.2.6/hpcinstall", line 554, in <module>                                                                                                           
    print term.bold_green("Hashdir:"), hashdir.hashdir(dirs.prefix), os.path.abspath(os.path.expanduser(dirs.prefix))                                                                       
  File "/glade/u/apps/dav/opt/hpcinstall/1.2.6/hashdir.py", line 24, in hashdir                                                                                                             
    f1 = open(filepath, 'rb')                                                                                                                                                               
IOError: [Errno 2] No such file or directory: '/glade/scratch/csgteam/dav/test_installs/pgi/19.3/linux86-64-llvm/19.3/REDIST/libnuma.so'
Connection to localhost closed.

**Comment by davidedelvento** [comment]
@siddsghosh 

`hashdir` loops over every file and directory besides the one(s) explicitly excluded, then opens each one of them and computes the hashes of each, which are eventually combined into one.

Obviously a broken symbolic link cannot be opened and breaks as you described.

I can easily ignore the error that opening a non-existing file will cause, while still using the metadata about the presence of the symbolic link (name, target, permissions -- see https://github.com/NCAR/HPCinstall/blob/a74ea41975b6741205a0e1444618008b25ce110a/hashdir.py#L31-L41 ) if that is the desired behavior.
